const personaggi = [
    ["isaac", 0.88],
    ["magdalene", 0.99],
    ["cain", 0.96],
    ["judas", 0.98],
    ["bluebaby", 1.15],
    ["eve", 0.98],
    ["samson", 0.96],
    ["azazel", 0.96],
    ["lazarus", 0.96],
    ["eden", 2],
    ["lost", 0.91],
    ["lilith", 0.99],
    ["keeper", 1.25],
    ["apollyon", 1],
    ["forgotten", 0.90],
    ["bethany", 0.97],
    ["jacobesau", 1.40]
];

const completion = [
    ["piede", 500],
    ["cuoremamma",750],
    ["itlives", 750],
    ["satan", 1000],
    ["isaac", 1000],
    ["lamb", 1500],
    ["???", 1500],
    ["megasatan", 2500],
    ["bossrush", 1250],
    ["hush", 1500],
    ["delirium", 4000],
    ["dogma", 2500],
    ["beast", 3000],
    ["mother", 3500],
    ["greedier", 9999],
    ["greed", 9999]
];


function apriBoss(){
    document.querySelectorAll('.sezione').forEach(div => div.style.display='none');
    document.getElementById('menu-selezione').style.display = 'none';
    document.getElementById('bottone-indietro').style.display = 'block';
    document.getElementById('menu-boss').style.display = 'block';
}

function apriPartita(){
    document.querySelectorAll('.sezione').forEach(div => div.style.display='none');
    document.getElementById('menu-selezione').style.display = 'none';
    document.getElementById('bottone-indietro').style.display = 'block';
    document.getElementById('menu-partita').style.display = 'block';
}

function apriOggetti(){
    document.querySelectorAll('.sezione').forEach(div => div.style.display='none');
    document.getElementById('menu-selezione').style.display = 'none';
    document.getElementById('bottone-indietro').style.display = 'block';
    document.getElementById('menu-items').style.display = 'block';
}

function apriTempo(){
    document.querySelectorAll('.sezione').forEach(div => div.style.display='none');
    document.getElementById('menu-selezione').style.display = 'none';
    document.getElementById('bottone-indietro').style.display = 'block';
    document.getElementById('menu-tempo').style.display = 'block';
}

function apriStanza(){
    document.querySelectorAll('.sezione').forEach(div => div.style.display='none');
    document.getElementById('menu-selezione').style.display = 'none';
    document.getElementById('bottone-indietro').style.display = 'block';
}

function apriMorte(){
    document.querySelectorAll('.sezione').forEach(div => div.style.display='none');
    document.getElementById('menu-selezione').style.display = 'none';
    document.getElementById('bottone-indietro').style.display = 'block';
}

function tornaIndietro() {
    // Nasconde tutte le sezioni
    document.querySelectorAll('.sezione').forEach(div => div.style.display = 'block');
    document.querySelectorAll('[class*="menu-"]').forEach(div => div.style.display = 'none');
    // Mostra il menu
    document.getElementById('menu-selezione').style.display = 'flex';
    document.getElementById('bottone-indietro').style.display = 'none';
  }

function calcolaPunteggio(){
    const quality = {
        "skatole": 0,
        "boom": 0,
        "aquarter": 0,
        "deadbird": 0,
        "peagentboy": 0,
        "infestation": 0,
        "ankh": 0,
        "theblackbean": 0,
        "abel": 0,
        "momscoinpurse": 0,
        "box": 0,
        "guillotine": 0,
        "spiderbaby": 0,
        "tinyplanet": 0,
        "ecoli": 0,
        "keypiece1": 0,
        "keypiece2": 0,
        "littlebaggy": 0,
        "missingno": 0,
        "missingpage2": 0,
        "bobsbrain": 0,
        "bestbud": 0,
        "isaacsheart": 0,
        "strangeattractor": 0,
        "cursedeye": 0,
        "thewiz": 0,
        "curseofthetower": 0,
        "keybum": 0,
        "marked": 0,
        "blackpowder": 0,
        "obsessedfan": 0,
        "lingerbeans": 0,
        "varicoseveins": 0,
        "shade": 0,
        "hushy": 0,
        "leprosy": 0,
        "mysteryegg": 0,
        "mars": 0,
        "batterypack": 0,
        "birdcage": 0,
        "knifepiece1": 0,
        "knifepiece2": 0,
        "dadsnote": 0,
        "apoundofflesh": 0,
        "lilportal": 0,
        "tmtrainer": 0,
        "ibs": 0,
        "bbf": 0,
        "brotherbobby": 1,
        "lunch": 1,
        "dinner": 1,
        "dessert": 1,
        "breakfast": 1,
        "rottenmeat": 1,
        "woodenspoon": 1,
        "thebelt": 1,
        "momsunderwear": 1,
        "momsheels": 1,
        "momslipstick": 1,
        "magneto": 1,
        "treasuremap": 1,
        "momseye": 1,
        "theladder": 1,
        "sistermaggy": 1,
        "cubeofmeat": 1,
        "lokishorn": 1,
        "littlechubby": 1,
        "sackofpennies": 1,
        "robobaby": 1,
        "littlegish": 1,
        "thecommoncold": 1,
        "guardianangel": 1,
        "demonbaby": 1,
        "bobbybomb": 1,
        "foreveralone": 1,
        "bucketoflard": 1,
        "bombbag": 1,
        "bobscurse": 1,
        "bumfriend": 1,
        "celticcross": 1,
        "ghostbaby": 1,
        "harlequinbaby": 1,
        "rainbowbaby": 1,
        "stemcells": 1,
        "guppyshairball": 1,
        "magic8ball": 1,
        "momseyeshadow": 1,
        "midastouch": 1,
        "fannypack": 1,
        "ballofbandages": 1,
        "buttbombs": 1,
        "gnawedleaf": 1,
        "guppyscollar": 1,
        "anemic": 1,
        "antigravity": 1,
        "piggybank": 1,
        "experimentaltreatment": 1,
        "bluemap": 1,
        "bogobombs": 1,
        "hotbombs": 1,
        "smartfly": 1,
        "robobaby20": 1,
        "headlessbaby": 1,
        "lilhaunt": 1,
        "bigfan": 1,
        "sissylonglegs": 1,
        "punchingbag": 1,
        "taurus": 1,
        "leo": 1,
        "libra": 1,
        "thunderthighs": 1,
        "gemini": 1,
        "onlyfriend": 1,
        "samosnschains": 1,
        "theludovicotechnique": 1,
        "lazarusrags": 1,
        "brokenwatch": 1,
        "safetypin": 1,
        "caffeinepill": 1,
        "latchkey": 1,
        "matchbook": 1,
        "asnack": 1,
        "friendzone": 1,
        "scatterbombs": 1,
        "stickybombs": 1,
        "epiphora": 1,
        "burstingsack": 1,
        "lilgurdy": 1,
        "bumbo": 1,
        "betrayal": 1,
        "zodiac": 1,
        "godsflesh": 1,
        "spearofdestiny": 1,
        "spidermod": 1,
        "fartingbaby": 1,
        "gbbug": 1,
        "cambionconception": 1,
        "immaculateconception": 1,
        "nightlight": 1,
        "papafly": 1,
        "myshadow": 1,
        "lilloki": 1,
        "milk": 1,
        "darkprincescrown": 1,
        "deadtooth": 1,
        "shardofglass": 1,
        "metalplate": 1,
        "dadslostcoin": 1,
        "midnightsnack": 1,
        "glaucoma": 1,
        "finger": 1,
        "depression": 1,
        "kingbaby": 1,
        "bigchubby": 1,
        "adrenaline": 1,
        "duality": 1,
        "greedsgullet": 1,
        "largezit": 1,
        "momsrazor": 1,
        "bloodshotteye": 1,
        "angryfly": 1,
        "fastbombs": 1,
        "lildelirium": 1,
        "pop": 1,
        "deathslist": 1,
        "lilspewer": 1,
        "marrow": 1,
        "slippedrib": 1,
        "hallowedground": 1,
        "pointyrib": 1,
        "jawbone": 1,
        "2spooky": 1,
        "eyesore": 1,
        "ithurts": 1,
        "almondmilk": 1,
        "nancybombs": 1,
        "bloodpuppy": 1,
        "divineintervention": 1,
        "bloodoath": 1,
        "monstrance": 1,
        "dirtymind": 1,
        "rocketinajar": 1,
        "boiledbaby": 1,
        "lostsoul": 1,
        "boosterpack": 1,
        "evilcharm": 1,
        "purgatory": 1,
        "akeldama": 1,
        "consolationprize": 1,
        "tinytoma": 1,
        "fruityplum": 1,
        "cubebaby": 1,
        "vasculitis": 1,
        "giantcell": 1,
        "tropicamide": 1,
        "strawman": 1,
        "candyheart": 1,
        "spiritshackles": 1,
        "crackedorb": 1,
        "emptyheart": 1,
        "astralprojection": 1,
        "soullocket": 1,
        "sanguinebond": 1,
        "vanishingtwin": 1,
        "vengefulspirit": 1,
        "supper": 1,
        "hemoptysis": 1,
        "ghostbombs": 1,
        "thecompass": 1,
        "distantadmiration": 1,
        "1up": 2,
        "120volt": 2,
        "3dollarbill": 2,
        "45volts": 2,
        "7seals": 2,
        "9volt": 2,
        "abarofsoap": 2,
        "acidbaby": 2,
        "analogstick": 2,
        "aquarius": 2,
        "aries": 2,
        "azazelsrage": 2,
        "balloftar": 2,
        "bellybutton": 2,
        "bffs": 2,
        "blacklotus": 2,
        "blanket": 2,
        "bloodbag": 2,
        "bloodbombs": 2,
        "bloodclot": 2,
        "bloodygust": 2,
        "bloodylust": 2,
        "bomberboy": 2,
        "bonespurs": 2,
        "bozo": 2,
        "brimstonebombs": 2,
        "buddyinabox": 2,
        "cainsothereye": 2,
        "censer": 2,
        "chargedbaby": 2,
        "charmofthevampire": 2,
        "chemicalpeel": 2,
        "circleofprotection": 2,
        "conehead": 2,
        "contagion": 2,
        "continuum": 2,
        "contractfrombelow": 2,
        "crackjacks": 2,
        "cupidsarrow": 2,
        "dadsring": 2,
        "deadonion": 2,
        "deeppockets": 2,
        "dogtooth": 2,
        "dreamcatcher": 2,
        "emptyvessel": 2,
        "evileye": 2,
        "eyeofgreed": 2,
        "falsephd": 2,
        "fatesreward": 2,
        "fireminds": 2,
        "flatstone": 2,
        "freezerbaby": 2,
        "fruitcake": 2,
        "gimpy": 2,
        "glitterbombs": 2,
        "glyphofbalance": 2,
        "guppyseye": 2,
        "guppystail": 2,
        "habit": 2,
        "haloofflies": 2,
        "headofthekeeper": 2,
        "hivemind": 2,
        "hungrysouls": 2,
        "hypercoagulation": 2,
        "infamy": 2,
        "innerchild": 2,
        "ironbar": 2,
        "isaacstomb": 2,
        "jesusjuice": 2,
        "juicysack": 2,
        "jumpercables": 2,
        "jupiter": 2,
        "keeperskin": 2,
        "kidneystone": 2,
        "knockoutdrops": 2,
        "leech": 2,
        "lilabaddon": 2,
        "lilbrimstone": 2,
        "lilchest": 2,
        "lilmonstro": 2,
        "littlechad": 2,
        "littlesteven": 2,
        "lodestone": 2,
        "lostcontact": 2,
        "lostfly": 2,
        "luckyfoot": 2,
        "maggysbow": 2,
        "magicscab": 2,
        "marbles": 2,
        "meat": 2,
        "membercard": 2,
        "mercurius": 2,
        "minimush": 2,
        "momspearls": 2,
        "momsperfume": 2,
        "momspurse": 2,
        "momswig": 2,
        "mongobaby": 2,
        "monstroslung": 2,
        "montezumasrevenge": 2,
        "mrmega": 2,
        "multidimensionalbaby": 2,
        "mysterysack": 2,
        "numberone": 2,
        "numbertwo": 2,
        "ocularrift": 2,
        "oddmushroomlarge": 2,
        "oddmushroomthin": 2,
        "oldbandage": 2,
        "options": 2,
        "orphansocks": 2,
        "ouijaboard": 2,
        "paytoplay": 2,
        "phd": 2,
        "pisces": 2,
        "pjs": 2,
        "placenta": 2,
        "playdoughcookie": 2,
        "pokego": 2,
        "polydactyly": 2,
        "pupuladuplex": 2,
        "quints": 2,
        "rawliver": 2,
        "redstew": 2,
        "redemption": 2,
        "restock": 2,
        "roidrage": 2,
        "rosary": 2,
        "rottentomato": 2,
        "sackofsacks": 2,
        "sacrificialdagger": 2,
        "sadbombs": 2,
        "saturnus": 2,
        "scapular": 2,
        "screw": 2,
        "serpentskiss": 2,
        "sharpplug": 2,
        "skeletonkey": 2,
        "sol": 2,
        "soymilk": 2,
        "speedball": 2,
        "spelunkerhat": 2,
        "spiderbite": 2,
        "starterdeck": 2,
        "steamsale": 2,
        "stigmata": 2,
        "stye": 2,
        "sulfuricacid": 2,
        "superbandage": 2,
        "swornprotector": 2,
        "tarotcloth": 2,
        "technology2": 2,
        "thebattery": 2,
        "theintruder": 2,
        "thenegative": 2,
        "thepeeper": 2,
        "thepolaroid": 2,
        "theswarm": 2,
        "thevirus": 2,
        "toothandnail": 2,
        "transcendence": 2,
        "trinityshield": 2,
        "venus": 2,
        "virgo": 2,
        "voodoohead": 2,
        "whoreofbabylon": 2,
        "xrayvision": 2,
        "yolisten": 2,
        "8inchnails": 3,
        "adollar": 3,
        "alumpofcoal": 3,
        "abaddon": 3,
        "actofcontrition": 3,
        "angelicprism": 3,
        "apple": 3,
        "athame": 3,
        "backstabber": 3,
        "bellyjelly": 3,
        "binky": 3,
        "birdseye": 3,
        "birthright": 3,
        "blackcandle": 3,
        "bloodofthemartyr": 3,
        "bluecap": 3,
        "botfly": 3,
        "brittlebones": 3,
        "brokenmodem": 3,
        "camoundies": 3,
        "cancer": 3,
        "capricorn": 3,
        "carbattery": 3,
        "cardreading": 3,
        "catoninetails": 3,
        "ceremonialrobes": 3,
        "championbelt": 3,
        "chaos": 3,
        "chocolatemilk": 3,
        "compoudfracture": 3,
        "cricketsbody": 3,
        "daddylonglegs": 3,
        "darkbum": 3,
        "darkmatter": 3,
        "deadcat": 3,
        "deaddove": 3,
        "deadeye": 3,
        "deathstouch": 3,
        "divorcepapers": 3,
        "dogma": 3,
        "drybaby": 3,
        "echochamber": 3,
        "edensblessing": 3,
        "eucharist": 3,
        "euthanasia": 3,
        "evesmascara": 3,
        "explosivo": 3,
        "eyedrops": 3,
        "eyeofbelial": 3,
        "eyeoftheoccult": 3,
        "fate": 3,
        "ghostpepper": 3,
        "glasseye": 3,
        "goathead": 3,
        "growthormones": 3,
        "heartbreaker": 3,
        "holygrail": 3,
        "holylight": 3,
        "holywater": 3,
        "hosthat": 3,
        "humbleingbundle": 3,
        "immaculateheart": 3,
        "infestation2": 3,
        "jacobsladder": 3,
        "judasshadow": 3,
        "keeperssack": 3,
        "lachryphagy": 3,
        "leadpencil": 3,
        "lildumpy": 3,
        "littlehorn": 3,
        "lordofthepit": 3,
        "luna": 3,
        "lustyblood": 3,
        "mawofthevoid": 3,
        "mitre": 3,
        "momscontacts": 3,
        "momskey": 3,
        "momsring": 3,
        "moneypower": 3,
        "moreoptions": 3,
        "mrdolly": 3,
        "mucormycosis": 3,
        "mutantspider": 3,
        "myreflection": 3,
        "mysteriousliquid": 3,
        "neptunus": 3,
        "parasitoid": 3,
        "paschalcandle": 3,
        "pentagram": 3,
        "pluto": 3,
        "proptosis": 3,
        "purity": 3,
        "pyro": 3,
        "rottenbaby": 3,
        "rubbercement": 3,
        "runebag": 3,
        "sackhead": 3,
        "sagittarius": 3,
        "salvation": 3,
        "sausage": 3,
        "schoolbag": 3,
        "scorpio": 3,
        "seraphim": 3,
        "sinusinfection": 3,
        "smbsuperfan": 3,
        "spiritofthenight": 3,
        "spiritsword": 3,
        "spoonbender": 3,
        "squeezy": 3,
        "stapler": 3,
        "starofbethlehem": 3,
        "steven": 3,
        "succubus": 3,
        "synthoil": 3,
        "tech5": 3,
        "technology": 3,
        "technologyzero": 3,
        "terra": 3,
        "thebody": 3,
        "thehalo": 3,
        "theinnereye": 3,
        "themark": 3,
        "themind": 3,
        "themulligan": 3,
        "thepact": 3,
        "theparasite": 3,
        "therelic": 3,
        "thesadonion": 3,
        "thesmallrock": 3,
        "thesoul": 3,
        "thestairway": 3,
        "theresoptions": 3,
        "toothpicks": 3,
        "tornphoto": 3,
        "toughlove": 3,
        "toxicshock": 3,
        "tractorbeam": 3,
        "trisagion": 3,
        "uranus": 3,
        "wirecoathanger": 3,
        "wormfriend": 3,
        "2020": 4,
        "bingeeater": 4,
        "brimstone": 4,
        "brokenshovel": 4,
        "csection": 4,
        "cricketshead": 4,
        "crownoflight": 4,
        "drfetus": 4,
        "epicfetus": 4,
        "glitchedcrown": 4,
        "godhead": 4,
        "haemolacria": 4,
        "holymantle": 4,
        "incubus": 4,
        "ipecac": 4,
        "magicmushroom": 4,
        "momsknife": 4,
        "polyphemus": 4,
        "psyfly": 4,
        "pyromaniac": 4,
        "revelation": 4,
        "rockbottom": 4,
        "sacredheart": 4,
        "sacredorb": 4,
        "stopwatch": 4,
        "techx": 4,
        "thewafer": 4,
        "twistedpair": 4
    }
}

document.addEventListener('DOMContentLoaded', () => {
    const boss = new Choices('#select-boss', {
        removeItemButton: true,
        choices: [
            {
                value: 'piede',
                label: "Piede di Mamma"
            },
            {
                value: 'cuoremamma', 
                label: "Cuore di Mamma"
            },
            {
                value: 'itlives', 
                label: "It Lives"
            },
            {
                value: 'satan', 
                label: "Satana"
            },
            {
                value: 'isaac', 
                label: "Isaac"
            },
            {
                value: 'lamb', 
                label: "The Lamb"
            },
            {
                value: '???', 
                label: "???"
            },
            {
                value: 'megasatan', 
                label: "Mega Satana"
            },
            {
                value: 'hush', 
                label: "Hush"
            },
            {
                value: 'dogma', 
                label: "Dogma"
            },
            {
                value: 'delirium', 
                label: "Delirium"
            },
            {
                value: 'mother', 
                label: "Mother"
            },
            {
                value: 'beast', 
                label: "The Beast"
            },
            {
                value: 'greed', 
                label: "Ultra Greed"
            },
            {
                value: 'greedier', 
                label: "Ultra Greedier"
            },
        ],
        shouldSort: false,
        noResultsText: "Nessun boss trovato :c",
        noChoicesText: "Boss finiti :D",
        itemSelectText: "Invio per selezionare"
    });

    const items = new Choices('#select-items', {
        removeItemButton: true,
        choices: [
            { value: 'skatole', label: 'Skatole' },
            { value: 'boom', label: 'Boom!' },
            { value: 'aquarter', label: 'A Quarter' },
            { value: 'deadbird', label: 'Dead Bird' },
            { value: 'peagentboy', label: 'Peagent Boy' },
            { value: 'infestation', label: 'Infestation' },
            { value: 'ankh', label: 'Ankh' },
            { value: 'theblackbean', label: 'The Black Bean' },
            { value: 'abel', label: 'Abel' },
            { value: 'momscoinpurse', label: "Mom's Coin Purse" },
            { value: 'box', label: 'Box' },
            { value: 'guillotine', label: 'Guillotine' },
            { value: 'spiderbaby', label: 'Spiderbaby' },
            { value: 'tinyplanet', label: 'Tiny Planet' },
            { value: 'ecoli', label: 'E. Coli' },
            { value: 'keypiece1', label: 'Key Piece 1' },
            { value: 'keypiece2', label: 'Key Piece 2' },
            { value: 'littlebaggy', label: 'Little Baggy' },
            { value: 'missingno', label: 'Missing No.' },
            { value: 'missingpage2', label: 'Missing Page 2' },
            { value: 'bobsbrain', label: "Bob's Brain" },
            { value: 'bestbud', label: 'Best Bud' },
            { value: 'isaacsheart', label: "Isaac's Heart" },
            { value: 'strangeattractor', label: 'Strange Attractor' },
            { value: 'cursedeye', label: 'Cursed Eye' },
            { value: 'thewiz', label: 'The Wiz' },
            { value: 'curseofthetower', label: 'Curse of the Tower' },
            { value: 'keybum', label: 'Key Bum' },
            { value: 'marked', label: 'Marked' },
            { value: 'blackpowder', label: 'Black Powder' },
            { value: 'obsessedfan', label: 'Obsessed Fan' },
            { value: 'lingerbeans', label: 'Linger Beans' },
            { value: 'varicoseveins', label: 'Varicose Veins' },
            { value: 'shade', label: 'Shade' },
            { value: 'hushy', label: 'Hushy' },
            { value: 'leprosy', label: 'Leprosy' },
            { value: 'mysteryegg', label: 'Mystery Egg' },
            { value: 'mars', label: 'Mars' },
            { value: 'batterypack', label: 'Battery Pack' },
            { value: 'birdcage', label: 'Bird Cage' },
            { value: 'knifepiece1', label: 'Knife Piece 1' },
            { value: 'knifepiece2', label: 'Knife Piece 2' },
            { value: 'dadsnote', label: "Dad's Note" },
            { value: 'apoundofflesh', label: 'A Pound of Flesh' },
            { value: 'lilportal', label: 'Lil Portal' },
            { value: 'tmtrainer', label: 'TMTRAINER' },
            { value: 'ibs', label: 'IBS' },
            { value: 'bbf', label: 'BBF' },
            { value: 'brotherbobby', label: 'Brother Bobby' },
            { value: 'lunch', label: 'Lunch' },
            { value: 'dinner', label: 'Dinner' },
            { value: 'dessert', label: 'Dessert' },
            { value: 'breakfast', label: 'Breakfast' },
            { value: 'rottenmeat', label: 'Rotten Meat' },
            { value: 'woodenspoon', label: 'Wooden Spoon' },
            { value: 'thebelt', label: 'The Belt' },
            { value: 'momsunderwear', label: "Mom's Underwear" },
            { value: 'momsheels', label: "Mom's Heels" },
            { value: 'momslipstick', label: "Mom's Lipstick" },
            { value: 'magneto', label: 'Magneto' },
            { value: 'treasuremap', label: 'Treasure Map' },
            { value: 'momseye', label: "Mom's Eye" },
            { value: 'theladder', label: 'The Ladder' },
            { value: 'sistermaggy', label: 'Sister Maggy' },
            { value: 'cubeofmeat', label: 'Cube of Meat' },
            { value: 'lokishorn', label: "Loki's Horn" },
            { value: 'littlechubby', label: 'Little Chubby' },
            { value: 'sackofpennies', label: 'Sack of Pennies' },
            { value: 'robobaby', label: 'Robo Baby' },
            { value: 'littlegish', label: 'Little Gish' },
            { value: 'thecommoncold', label: 'The Common Cold' },
            { value: 'guardianangel', label: 'Guardian Angel' },
            { value: 'demonbaby', label: 'Demon Baby' },
            { value: 'bobbybomb', label: 'Bobby-Bomb' },
            { value: 'foreveralone', label: 'Forever Alone' },
            { value: 'bucketoflard', label: 'Bucket of Lard' },
            { value: 'bombbag', label: 'Bomb Bag' },
            { value: 'bobscurse', label: "Bob's Curse" },
            { value: 'bumfriend', label: 'Bum Friend' },
            { value: 'celticcross', label: 'Celtic Cross' },
            { value: 'ghostbaby', label: 'Ghost Baby' },
            { value: 'harlequinbaby', label: 'Harlequin Baby' },
            { value: 'rainbowbaby', label: 'Rainbow Baby' },
            { value: 'stemcells', label: 'Stem Cells' },
            { value: 'guppyshairball', label: "Guppy's Hairball" },
            { value: 'magic8ball', label: 'Magic 8 Ball' },
            { value: 'momseyeshadow', label: "Mom's Eyeshadow" },
            { value: 'midastouch', label: "Midas' Touch" },
            { value: 'fannypack', label: 'Fanny Pack' },
            { value: 'ballofbandages', label: 'Ball of Bandages' },
            { value: 'buttbombs', label: 'Butt Bombs' },
            { value: 'gnawedleaf', label: 'Gnawed Leaf' },
            { value: 'guppyscollar', label: "Guppy's Collar" },
            { value: 'anemic', label: 'Anemic' },
            { value: 'antigravity', label: 'Anti-Gravity' },
            { value: 'piggybank', label: 'Piggy Bank' },
            { value: 'experimentaltreatment', label: 'Experimental Treatment' },
            { value: 'bluemap', label: 'Blue Map' },
            { value: 'bogobombs', label: 'BOGO Bombs' },
            { value: 'hotbombs', label: 'Hot Bombs' },
            { value: 'smartfly', label: 'Smart Fly' },
            { value: 'robobaby20', label: 'Robo-Baby 2.0' },
            { value: 'headlessbaby', label: 'Headless Baby' },
            { value: 'lilhaunt', label: 'Lil Haunt' },
            { value: 'bigfan', label: 'Big Fan' },
            { value: 'sissylonglegs', label: 'Sissy Longlegs' },
            { value: 'punchingbag', label: 'Punching Bag' },
            { value: 'taurus', label: 'Taurus' },
            { value: 'leo', label: 'Leo' },
            { value: 'libra', label: 'Libra' },
            { value: 'thunderthighs', label: 'Thunder Thighs' },
            { value: 'gemini', label: 'Gemini' },
            { value: 'onlyfriend', label: "???'s Only Friend" },
            { value: 'samosnschains', label: "Samson's Chains" },
            { value: 'theludovicotechnique', label: 'The Ludovico Technique' },
            { value: 'lazarusrags', label: "Lazarus' Rags" },
            { value: 'brokenwatch', label: 'Broken Watch' },
            { value: 'safetypin', label: 'Safety Pin' },
            { value: 'caffeinepill', label: 'Caffeine Pill' },
            { value: 'latchkey', label: 'Latch Key' },
            { value: 'matchbook', label: 'Match Book' },
            { value: 'asnack', label: 'A Snack' },
            { value: 'friendzone', label: 'Friend Zone' },
            { value: 'scatterbombs', label: 'Scatter Bombs' },
            { value: 'stickybombs', label: 'Sticky Bombs' },
            { value: 'epiphora', label: 'Epiphora' },
            { value: 'burstingsack', label: 'Bursting Sack' },
            { value: 'lilgurdy', label: 'Lil Gurdy' },
            { value: 'bumbo', label: 'Bumbo' },
            { value: 'betrayal', label: 'Betrayal' },
            { value: 'zodiac', label: 'Zodiac' },
            { value: 'godsflesh', label: "God's Flesh" },
            { value: 'spearofdestiny', label: 'Spear of Destiny' },
            { value: 'spidermod', label: 'Spider Mod' },
            { value: 'fartingbaby', label: 'Farting Baby' },
            { value: 'gbbug', label: 'GB Bug' },
            { value: 'cambionconception', label: 'Cambion Conception' },
            { value: 'immaculateconception', label: 'Immaculate Conception' },
            { value: 'nightlight', label: 'Night Light' },
            { value: 'papafly', label: 'Papa Fly' },
            { value: 'myshadow', label: 'My Shadow' },
            { value: 'lilloki', label: 'Lil Loki' },
            { value: 'milk', label: 'Milk!' },
            { value: 'darkprincescrown', label: "Dark Prince's Crown" },
            { value: 'deadtooth', label: 'Dead Tooth' },
            { value: 'shardofglass', label: 'Shard of Glass' },
            { value: 'metalplate', label: 'Metal Plate' },
            { value: 'dadslostcoin', label: "Dad's Lost Coin" },
            { value: 'midnightsnack', label: 'Midnight Snack' },
            { value: 'glaucoma', label: 'Glaucoma' },
            { value: 'finger', label: 'Finger!' },
            { value: 'depression', label: 'Depression' },
            { value: 'kingbaby', label: 'King Baby' },
            { value: 'bigchubby', label: 'Big Chubby' },
            { value: 'adrenaline', label: 'Adrenaline' },
            { value: 'duality', label: 'Duality' },
            { value: 'greedsgullet', label: "Greed's Gullet" },
            { value: 'largezit', label: 'Large Zit' },
            { value: 'momsrazor', label: "Mom's Razor" },
            { value: 'bloodshotteye', label: 'Bloodshot Eye' },
            { value: 'angryfly', label: 'Angry Fly' },
            { value: 'fastbombs', label: 'Fast Bombs' },
            { value: 'lildelirium', label: 'Lil Delirium' },
            { value: 'pop', label: 'POP!' },
            { value: 'deathslist', label: "Death's List" },
            { value: 'lilspewer', label: 'Lil Spewer' },
            { value: 'marrow', label: 'Marrow' },
            { value: 'slippedrib', label: 'Slipped Rib' },
            { value: 'hallowedground', label: 'Hallowed Ground' },
            { value: 'pointyrib', label: 'Pointy Rib' },
            { value: 'jawbone', label: 'Jaw Bone' },
            { value: '2spooky', label: '2Spooky' },
            { value: 'eyesore', label: 'Eye Sore' },
            { value: 'ithurts', label: 'It Hurts' },
            { value: 'almondmilk', label: 'Almond Milk' },
            { value: 'nancybombs', label: 'Nancy Bombs' },
            { value: 'bloodpuppy', label: 'Blood Puppy' },
            { value: 'divineintervention', label: 'Divine Intervention' },
            { value: 'bloodoath', label: 'Blood Oath' },
            { value: 'monstrance', label: 'Monstrance' },
            { value: 'dirtymind', label: 'Dirty Mind' },
            { value: 'rocketinajar', label: 'Rocket in a Jar' },
            { value: 'boiledbaby', label: 'Boiled Baby' },
            { value: 'lostsoul', label: 'Lost Soul' },
            { value: 'boosterpack', label: 'Booster Pack' },
            { value: 'evilcharm', label: 'Evil Charm' },
            { value: 'purgatory', label: 'Purgatory' },
            { value: 'akeldama', label: 'Akeldama' },
            { value: 'consolationprize', label: 'Consolation Prize' },
            { value: 'tinytoma', label: 'TinyToma' },
            { value: 'fruityplum', label: 'Fruity Plum' },
            { value: 'cubebaby', label: 'Cube Baby' },
            { value: 'vasculitis', label: 'Vasculitis' },
            { value: 'giantcell', label: 'Giant Cell' },
            { value: 'tropicamide', label: 'Tropicamide' },
            { value: 'strawman', label: 'Strawman' },
            { value: 'candyheart', label: 'Candy Heart' },
            { value: 'spiritshackles', label: 'Spirit Shackles' },
            { value: 'crackedorb', label: 'Cracked Orb' },
            { value: 'emptyheart', label: 'Empty Heart' },
            { value: 'astralprojection', label: 'Astral Projection' },
            { value: 'soullocket', label: 'Soul Locket' },
            { value: 'sanguinebond', label: 'Sanguine Bond' },
            { value: 'vanishingtwin', label: 'Vanishing Twin' },
            { value: 'vengefulspirit', label: 'Vengeful Spirit' },
            { value: 'supper', label: 'Supper' },
            { value: 'hemoptysis', label: 'Hemoptysis' },
            { value: 'ghostbombs', label: 'Ghost Bombs' },
            { value: 'thecompass', label: 'The Compass' },
            { value: 'distantadmiration', label: 'Distant Admiration' },
            { value: '1up', label: '1 Up' },
            { value: '120volt', label: '120 Volt' },
            { value: '3dollarbill', label: '3 Dollar Bill' },
            { value: '45volts', label: '4.5 Volts' },
            { value: '7seals', label: '7 Seals' },
            { value: '9volt', label: '9 Volt' },
            { value: 'abarofsoap', label: 'A Bar Of Soap' },
            { value: 'acidbaby', label: 'Acid Baby' },
            { value: 'analogstick', label: 'Analog Stick' },
            { value: 'aquarius', label: 'Aquarius' },
            { value: 'aries', label: 'Aries' },
            { value: 'azazelsrage', label: 'Azazel\'s Rage' },
            { value: 'balloftar', label: 'Ball Of Tar' },
            { value: 'bellybutton', label: 'Belly Button' },
            { value: 'bffs', label: 'BFFs!' },
            { value: 'blacklotus', label: 'Black Lotus' },
            { value: 'blanket', label: 'Blanket' },
            { value: 'bloodbag', label: 'Blood Bag' },
            { value: 'bloodbombs', label: 'Blood Bombs' },
            { value: 'bloodclot', label: 'Blood Clot' },
            { value: 'bloodygust', label: 'Bloody Gust' },
            { value: 'bloodylust', label: 'Bloody Lust' },
            { value: 'bomberboy', label: 'Bomber Boy' },
            { value: 'bonespurs', label: 'Bone Spurs' },
            { value: 'bozo', label: 'Bozo' },
            { value: 'brimstonebombs', label: 'Brimstone Bombs' },
            { value: 'buddyinabox', label: 'Buddy In A Box' },
            { value: 'cainsothereye', label: 'Cain\'s Other Eye' },
            { value: 'censer', label: 'Censer' },
            { value: 'chargedbaby', label: 'Charged Baby' },
            { value: 'charmofthevampire', label: 'Charm Of The Vampire' },
            { value: 'chemicalpeel', label: 'Chemical Peel' },
            { value: 'circleofprotection', label: 'Circle Of Protection' },
            { value: 'conehead', label: 'Cone Head' },
            { value: 'contagion', label: 'Contagion' },
            { value: 'continuum', label: 'Continuum' },
            { value: 'contractfrombelow', label: 'Contract From Below' },
            { value: 'crackjacks', label: 'Crack Jacks' },
            { value: 'cupidsarrow', label: 'Cupid\'s Arrow' },
            { value: 'dadsring', label: 'Dad\'s Ring' },
            { value: 'deadonion', label: 'Dead Onion' },
            { value: 'deeppockets', label: 'Deep Pockets' },
            { value: 'dogtooth', label: 'Dog Tooth' },
            { value: 'dreamcatcher', label: 'Dream Catcher' },
            { value: 'emptyvessel', label: 'Empty Vessel' },
            { value: 'evileye', label: 'Evil Eye' },
            { value: 'eyeofgreed', label: 'Eye Of Greed' },
            { value: 'falsephd', label: 'False PHD' },
            { value: 'fatesreward', label: 'Fate\'s Reward' },
            { value: 'fireminds', label: 'Fire Minds' },
            { value: 'flatstone', label: 'Flat Stone' },
            { value: 'freezerbaby', label: 'Freezer Baby' },
            { value: 'fruitcake', label: 'Fruit Cake' },
            { value: 'gimpy', label: 'Gimpy' },
            { value: 'glitterbombs', label: 'Glitter Bombs' },
            { value: 'glyphofbalance', label: 'Glyph Of Balance' },
            { value: 'guppyseye', label: 'Guppy\'s Eye' },
            { value: 'guppystail', label: 'Guppy\'s Tail' },
            { value: 'habit', label: 'Habit' },
            { value: 'haloofflies', label: 'Halo Of Flies' },
            { value: 'headofthekeeper', label: 'Head Of The Keeper' },
            { value: 'hivemind', label: 'Hive Mind' },
            { value: 'hungrysouls', label: 'Hungry Souls' },
            { value: 'hypercoagulation', label: 'Hypercoagulation' },
            { value: 'infamy', label: 'Infamy' },
            { value: 'innerchild', label: 'Inner Child' },
            { value: 'ironbar', label: 'Iron Bar' },
            { value: 'isaacstomb', label: 'Isaac\'s Tomb' },
            { value: 'jesusjuice', label: 'Jesus Juice' },
            { value: 'juicysack', label: 'Juicy Sack' },
            { value: 'jumpercables', label: 'Jumper Cables' },
            { value: 'jupiter', label: 'Jupiter' },
            { value: 'keeperskin', label: 'Keeper\'s Kin' },
            { value: 'kidneystone', label: 'Kidney Stone' },
            { value: 'knockoutdrops', label: 'Knockout Drops' },
            { value: 'leech', label: 'Leech' },
            { value: 'lilabaddon', label: 'Lil Abaddon' },
            { value: 'lilbrimstone', label: 'Lil Brimstone' },
            { value: 'lilchest', label: 'Lil Chest' },
            { value: 'lilmonstro', label: 'Lil Monstro' },
            { value: 'littlechad', label: 'Little Chad' },
            { value: 'littlesteven', label: 'Little Steven' },
            { value: 'lodestone', label: 'Lodestone' },
            { value: 'lostcontact', label: 'Lost Contact' },
            { value: 'lostfly', label: 'Lost Fly' },
            { value: 'luckyfoot', label: 'Lucky Foot' },
            { value: 'maggysbow', label: 'Maggy\'s Bow' },
            { value: 'magicscab', label: 'Magic Scab' },
            { value: 'marbles', label: 'Marbles' },
            { value: 'meat', label: 'Meat!' },
            { value: 'membercard', label: 'Member Card' },
            { value: 'mercurius', label: 'Mercurius' },
            { value: 'minimush', label: 'Mini Mush' },
            { value: 'momspearls', label: 'Mom\'s Pearls' },
            { value: 'momsperfume', label: 'Mom\'s Perfume' },
            { value: 'momspurse', label: 'Mom\'s Purse' },
            { value: 'momswig', label: 'Mom\'s Wig' },
            { value: 'mongobaby', label: 'Mongo Baby' },
            { value: 'monstroslung', label: 'Monstro\'s Lung' },
            { value: 'montezumasrevenge', label: 'Montezuma\'s Revenge' },
            { value: 'mrmega', label: 'Mr. Mega' },
            { value: 'multidimensionalbaby', label: 'Multidimensional Baby' },
            { value: 'mysterysack', label: 'Mystery Sack' },
            { value: 'numberone', label: 'Number One' },
            { value: 'numbertwo', label: 'Number Two' },
            { value: 'ocularrift', label: 'Ocular Rift' },
            { value: 'oddmushroomlarge', label: 'Odd Mushroom (Large)' },
            { value: 'oddmushroomthin', label: 'Odd Mushroom (Thin)' },
            { value: 'oldbandage', label: 'Old Bandage' },
            { value: 'options', label: 'Options?' },
            { value: 'orphansocks', label: 'Orphan Socks' },
            { value: 'ouijaboard', label: 'Ouija Board' },
            { value: 'paytoplay', label: 'Pay To Play' },
            { value: 'phd', label: 'PHD' },
            { value: 'pisces', label: 'Pisces' },
            { value: 'pjs', label: 'PJS' },
            { value: 'placenta', label: 'Placenta' },
            { value: 'playdoughcookie', label: 'Playdough Cookie' },
            { value: 'pokego', label: 'Poke Go' },
            { value: 'polydactyly', label: 'Polydactyly' },
            { value: 'pupuladuplex', label: 'Pupula Duplex' },
            { value: 'quints', label: 'Quints' },
            { value: 'rawliver', label: 'Raw Liver' },
            { value: 'redstew', label: 'Red Stew' },
            { value: 'redemption', label: 'Redemption' },
            { value: 'restock', label: 'Restock' },
            { value: 'roidrage', label: 'Roid Rage' },
            { value: 'rosary', label: 'Rosary' },
            { value: 'rottentomato', label: 'Rotten Tomato' },
            { value: 'sackofsacks', label: 'Sack Of Sacks' },
            { value: 'sacrificialdagger', label: 'Sacrificial Dagger' },
            { value: 'sadbombs', label: 'Sad Bombs' },
            { value: 'saturnus', label: 'Saturnus' },
            { value: 'scapular', label: 'Scapular' },
            { value: 'screw', label: 'Screw' },
            { value: 'serpentskiss', label: 'Serpent\'s Kiss' },
            { value: 'sharpplug', label: 'Sharp Plug' },
            { value: 'skeletonkey', label: 'Skeleton Key' },
            { value: 'sol', label: 'Sol' },
            { value: 'soymilk', label: 'Soy Milk' },
            { value: 'speedball', label: 'Speed Ball' },
            { value: 'spelunkerhat', label: 'Spelunker Hat' },
            { value: 'spiderbite', label: 'Spider Bite' },
            { value: 'starterdeck', label: 'Starter Deck' },
            { value: 'steamsale', label: 'Steam Sale' },
            { value: 'stigmata', label: 'Stigmata' },
            { value: 'stye', label: 'Stye' },
            { value: 'sulfuricacid', label: 'Sulfuric Acid' },
            { value: 'superbandage', label: 'Super Bandage' },
            { value: 'swornprotector', label: 'Sworn Protector' },
            { value: 'tarotcloth', label: 'Tarot Cloth' },
            { value: 'technology2', label: 'Technology 2' },
            { value: 'thebattery', label: 'The Battery' },
            { value: 'theintruder', label: 'The Intruder' },
            { value: 'thenegative', label: 'The Negative' },
            { value: 'thepeeper', label: 'The Peeper' },
            { value: 'thepolaroid', label: 'The Polaroid' },
            { value: 'theswarm', label: 'The Swarm' },
            { value: 'thevirus', label: 'The Virus' },
            { value: 'toothandnail', label: 'Tooth And Nail' },
            { value: 'transcendence', label: 'Transcendence' },
            { value: 'trinityshield', label: 'Trinity Shield' },
            { value: 'venus', label: 'Venus' },
            { value: 'virgo', label: 'Virgo' },
            { value: 'voodoohead', label: 'Voodoo Head' },
            { value: 'whoreofbabylon', label: 'Whore Of Babylon' },
            { value: 'xrayvision', label: 'X-Ray Vision' },
            { value: 'yolisten', label: 'Yo Listen!' },
            { value: '8inchnails', label: '8 Inch Nails' },
            { value: 'adollar', label: 'A Dollar' },
            { value: 'alumpofcoal', label: 'A Lump Of Coal' },
            { value: 'abaddon', label: 'Abaddon' },
            { value: 'actofcontrition', label: 'Act Of Contrition' },
            { value: 'angelicprism', label: 'Angelic Prism' },
            { value: 'apple', label: 'Apple!' },
            { value: 'athame', label: 'Athame' },
            { value: 'backstabber', label: 'Backstabber' },
            { value: 'bellyjelly', label: 'Belly Jelly' },
            { value: 'binky', label: 'Binky' },
            { value: 'birdseye', label: 'Bird\'s Eye' },
            { value: 'birthright', label: 'Birthright' },
            { value: 'blackcandle', label: 'Black Candle' },
            { value: 'bloodofthemartyr', label: 'Blood Of The Martyr' },
            { value: 'bluecap', label: 'Blue Cap' },
            { value: 'botfly', label: 'Bot Fly' },
            { value: 'brittlebones', label: 'Brittle Bones' },
            { value: 'brokenmodem', label: 'Broken Modem' },
            { value: 'camoundies', label: 'Camo Undies' },
            { value: 'cancer', label: 'Cancer' },
            { value: 'capricorn', label: 'Capricorn' },
            { value: 'carbattery', label: 'Car Battery' },
            { value: 'cardreading', label: 'Card Reading' },
            { value: 'catoninetails', label: 'Cat-O-Nine-Tails' },
            { value: 'ceremonialrobes', label: 'Ceremonial Robes' },
            { value: 'championbelt', label: 'Champion Belt' },
            { value: 'chaos', label: 'Chaos' },
            { value: 'chocolatemilk', label: 'Chocolate Milk' },
            { value: 'compoudfracture', label: 'Compoud Fracture' },
            { value: 'cricketsbody', label: 'Cricket\'s Body' },
            { value: 'daddylonglegs', label: 'Daddy Longlegs' },
            { value: 'darkbum', label: 'Dark Bum' },
            { value: 'darkmatter', label: 'Dark Matter' },
            { value: 'deadcat', label: 'Dead Cat' },
            { value: 'deaddove', label: 'Dead Dove' },
            { value: 'deadeye', label: 'Dead Eye' },
            { value: 'deathstouch', label: 'Death\'s Touch' },
            { value: 'divorcepapers', label: 'Divorce Papers' },
            { value: 'dogma', label: 'Dogma' },
            { value: 'drybaby', label: 'Dry Baby' },
            { value: 'echochamber', label: 'Echo Chamber' },
            { value: 'edensblessing', label: 'Eden\'s Blessing' },
            { value: 'eucharist', label: 'Eucharist' },
            { value: 'euthanasia', label: 'Euthanasia' },
            { value: 'evesmascara', label: 'Eve\'s Mascara' },
            { value: 'explosivo', label: 'Explosivo' },
            { value: 'eyedrops', label: 'Eye Drops' },
            { value: 'eyeofbelial', label: 'Eye Of Belial' },
            { value: 'eyeoftheoccult', label: 'Eye Of The Occult' },
            { value: 'fate', label: 'Fate' },
            { value: 'ghostpepper', label: 'Ghost Pepper' },
            { value: 'glasseye', label: 'Glass Eye' },
            { value: 'goathead', label: 'Goat Head' },
            { value: 'growthormones', label: 'Growth Ormones' },
            { value: 'heartbreaker', label: 'Heartbreaker' },
            { value: 'holygrail', label: 'Holy Grail' },
            { value: 'holylight', label: 'Holy Light' },
            { value: 'holywater', label: 'Holy Water' },
            { value: 'hosthat', label: 'Host Hat' },
            { value: 'humbleingbundle', label: 'Humbleing Bundle' },
            { value: 'immaculateheart', label: 'Immaculate Heart' },
            { value: 'infestation2', label: 'Infestation 2' },
            { value: 'jacobsladder', label: 'Jacob\'s Ladder' },
            { value: 'judasshadow', label: 'Juda\'s Shadow' },
            { value: 'keeperssack', label: 'Keeper\'s Sack' },
            { value: 'lachryphagy', label: 'Lachryphagy' },
            { value: 'leadpencil', label: 'Lead Pencil' },
            { value: 'lildumpy', label: 'Lil Dumpy' },
            { value: 'littlehorn', label: 'Little Horn' },
            { value: 'lordofthepit', label: 'Lord Of The Pit' },
            { value: 'luna', label: 'Luna' },
            { value: 'lustyblood', label: 'Lusty Blood' },
            { value: 'mawofthevoid', label: 'Maw Of The Void' },
            { value: 'mitre', label: 'Mitre' },
            { value: 'momscontacts', label: 'Mom\'s Contacts' },
            { value: 'momskey', label: 'Mom\'s Key' },
            { value: 'momsring', label: 'Mom\'s Ring' },
            { value: 'moneypower', label: 'Money = Power' },
            { value: 'moreoptions', label: 'More Options' },
            { value: 'mrdolly', label: 'Mr. Dolly' },
            { value: 'mucormycosis', label: 'Mucormycosis' },
            { value: 'mutantspider', label: 'Mutant Spider' },
            { value: 'myreflection', label: 'My Reflection' },
            { value: 'mysteriousliquid', label: 'Mysterious Liquid' },
            { value: 'neptunus', label: 'Neptunus' },
            { value: 'parasitoid', label: 'Parasitoid' },
            { value: 'paschalcandle', label: 'Paschal Candle' },
            { value: 'pentagram', label: 'Pentagram' },
            { value: 'pluto', label: 'Pluto' },
            { value: 'proptosis', label: 'Proptosis' },
            { value: 'purity', label: 'Purity' },
            { value: 'pyro', label: 'Pyro' },
            { value: 'rottenbaby', label: 'Rotten Baby' },
            { value: 'rubbercement', label: 'Rubber Cement' },
            { value: 'runebag', label: 'Rune Bag' },
            { value: 'sackhead', label: 'Sack Head' },
            { value: 'sagittarius', label: 'Sagittarius' },
            { value: 'salvation', label: 'Salvation' },
            { value: 'sausage', label: 'Sausage' },
            { value: 'schoolbag', label: 'Schoolbag' },
            { value: 'scorpio', label: 'Scorpio' },
            { value: 'seraphim', label: 'Seraphim' },
            { value: 'sinusinfection', label: 'Sinus Infection' },
            { value: 'smbsuperfan', label: 'Smb Super Fan' },
            { value: 'spiritofthenight', label: 'Spirit Of The Night' },
            { value: 'spiritsword', label: 'Spirit Sword' },
            { value: 'spoonbender', label: 'Spoon Bender' },
            { value: 'squeezy', label: 'Squeezy' },
            { value: 'stapler', label: 'Stapler' },
            { value: 'starofbethlehem', label: 'Star Of Bethlehem' },
            { value: 'steven', label: 'Steven' },
            { value: 'succubus', label: 'Succubus' },
            { value: 'synthoil', label: 'Synthoil' },
            { value: 'tech5', label: 'Tech .5' },
            { value: 'technology', label: 'Technology' },
            { value: 'technologyzero', label: 'Technology Zero' },
            { value: 'terra', label: 'Terra' },
            { value: 'thebody', label: 'The Body' },
            { value: 'thehalo', label: 'The Halo' },
            { value: 'theinnereye', label: 'The Inner Eye' },
            { value: 'themark', label: 'The Mark' },
            { value: 'themind', label: 'The Mind' },
            { value: 'themulligan', label: 'The Mulligan' },
            { value: 'thepact', label: 'The Pact' },
            { value: 'theparasite', label: 'The Parasite' },
            { value: 'therelic', label: 'The Relic' },
            { value: 'thesadonion', label: 'The Sad Onion' },
            { value: 'thesmallrock', label: 'The Small Rock' },
            { value: 'thesoul', label: 'The Soul' },
            { value: 'thestairway', label: 'The Stairway' },
            { value: 'theresoptions', label: 'There\'s Options' },
            { value: 'toothpicks', label: 'Tooth Picks' },
            { value: 'tornphoto', label: 'Torn Photo' },
            { value: 'toughlove', label: 'Tough Love' },
            { value: 'toxicshock', label: 'Toxic Shock' },
            { value: 'tractorbeam', label: 'Tractor Beam' },
            { value: 'trisagion', label: 'Trisagion' },
            { value: 'uranus', label: 'Uranus' },
            { value: 'wirecoathanger', label: 'Wire Coat Hanger' },
            { value: 'wormfriend', label: 'Worm Friend' },
            { value: '2020', label: '20/20' },
            { value: 'bingeeater', label: 'Binge Eater' },
            { value: 'brimstone', label: 'Brimstone' },
            { value: 'brokenshovel', label: 'Broken Shovel' },
            { value: 'csection', label: 'C Section' },
            { value: 'cricketshead', label: 'Cricket\'s Head' },
            { value: 'crownoflight', label: 'Crown Of Light' },
            { value: 'drfetus', label: 'Dr. Fetus' },
            { value: 'epicfetus', label: 'Epic Fetus' },
            { value: 'glitchedcrown', label: 'Glitched Crown' },
            { value: 'godhead', label: 'Godhead' },
            { value: 'haemolacria', label: 'Haemolacria' },
            { value: 'holymantle', label: 'Holy Mantle' },
            { value: 'incubus', label: 'Incubus' },
            { value: 'ipecac', label: 'Ipecac' },
            { value: 'magicmushroom', label: 'Magic Mushroom' },
            { value: 'momsknife', label: 'Mom\'s Knife' },
            { value: 'polyphemus', label: 'Polyphemus' },
            { value: 'psyfly', label: 'Psy Fly' },
            { value: 'pyromaniac', label: 'Pyromaniac' },
            { value: 'revelation', label: 'Revelation' },
            { value: 'rockbottom', label: 'Rock Bottom' },
            { value: 'sacredheart', label: 'Sacred Heart' },
            { value: 'sacredorb', label: 'Sacred Orb' },
            { value: 'stopwatch', label: 'Stop Watch' },
            { value: 'techx', label: 'Tech X' },
            { value: 'thewafer', label: 'The Wafer' },
            { value: 'twistedpair', label: 'Twisted Pair' }
        ],
        shouldSort: false,
        noResultsText: "Nessun item trovato :c",
        noChoicesText: "non ho idea di come tu sia arrivato qui, davvero complimenti",
        itemSelectText: "Invio per selezionare"
    });

    const partita = new Choices('#select-partita', {
        choices: [
            {
                value: '1',
                label: "Prima"
            },
            {
                value: '2', 
                label: "Seconda"
            },
        ],
        shouldSort: false,
        itemSelectText: "Invio per selezionare",
        addItems: false,
        searchEnabled: false
    });
});
